name: CI on feature branches

on:
  push:
    branches:
      - feat/*
      - fix/*
  pull_request:
    branches:
      - feat/*
      - fix/*

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '23'

      - name: Install frontend dependencies
        run: npm install

      - name: Run Jest tests on frontend
        run: npm run test
